version: "3.2"

services:
  brokerage-api:
    image: brokerage-api
    build:
     context: .
     dockerfile: BrokerageApi/Dockerfile
     args:
     - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=testdb;Username=postgres;Password=mypassword
    depends_on:
      - dev-database

  dev-database:
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  brokerage-api-test:
    image: brokerage-api-test
    build:
      context: .
      dockerfile: BrokerageApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      - CONNECTION_STRING=Host=test-database;Port=5432;Database=testdb;Username=postgres;Password=mypassword
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
    depends_on:
      - test-database

  test-database:
    image: postgres:12
    ports:
      - 5435:5432
    env_file:
      - database.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
