// <auto-generated />
using System;
using System.Collections.Generic;
using BrokerageApi.V1.Infrastructure;
using BrokerageApi.V1.Infrastructure.AuditEvents;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace V1.Infrastructure.Migrations
{
    [DbContext(typeof(BrokerageContext))]
    [Migration("20220718131646_AddPaymentCycleToElementType")]
    partial class AddPaymentCycleToElementType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "amendment_status", new[] { "in_progress", "resolved" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "audit_event_type", new[] { "referral_broker_assignment", "referral_broker_reassignment", "element_ended", "element_cancelled", "element_suspended", "care_package_ended", "care_package_cancelled", "care_package_suspended", "referral_archived", "import_note", "care_package_budget_approver_assigned", "care_package_approved", "amendment_requested", "care_charges_confirmed", "follow_up_requested" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "care_charge_status", new[] { "new", "existing", "termination", "suspension", "cancellation" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "element_billing_type", new[] { "supplier", "customer", "none", "ccg" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "element_cost_type", new[] { "hourly", "daily", "weekly", "transport", "one_off" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "element_status", new[] { "in_progress", "awaiting_approval", "approved", "inactive", "active", "ended", "suspended", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "element_type_type", new[] { "service", "provisional_care_charge", "confirmed_care_charge", "nursing_care" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "follow_up_status", new[] { "in_progress", "resolved" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_cycle", new[] { "weekly", "fortnightly", "four_weekly", "varying", "once" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "provider_type", new[] { "framework", "spot" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "referral_status", new[] { "unassigned", "in_review", "assigned", "on_hold", "archived", "in_progress", "awaiting_approval", "approved", "active", "ended", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "brokerage_assistant", "broker", "approver", "care_charges_officer", "referrer" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "workflow_type", new[] { "assessment", "review", "reassessment", "historic" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.AuditEvents.AuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<AuditEventType>("EventType")
                        .HasColumnType("audit_event_type")
                        .HasColumnName("event_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int?>("ReferralId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("referral_id")
                        .HasComputedColumnSql("(metadata->>'referralId')::integer", true);

                    b.Property<string>("SocialCareId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("social_care_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("ReferralId")
                        .HasDatabaseName("ix_audit_events_referral_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_events_user_id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.CarePackage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("AssignedApproverId")
                        .HasColumnType("text")
                        .HasColumnName("assigned_approver_id");

                    b.Property<string>("AssignedBrokerId")
                        .HasColumnType("text")
                        .HasColumnName("assigned_broker_id");

                    b.Property<CareChargeStatus>("CareChargeStatus")
                        .HasColumnType("care_charge_status")
                        .HasColumnName("care_charge_status");

                    b.Property<Instant?>("CareChargesConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("care_charges_confirmed_at");

                    b.Property<string>("CarePackageName")
                        .HasColumnType("text")
                        .HasColumnName("care_package_name");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EstimatedYearlyCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_yearly_cost");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form_name");

                    b.Property<bool>("IsResidential")
                        .HasColumnType("boolean")
                        .HasColumnName("is_residential");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal?>("OneOffPayment")
                        .HasColumnType("numeric")
                        .HasColumnName("one_off_payment");

                    b.Property<string>("PrimarySupportReason")
                        .HasColumnType("text")
                        .HasColumnName("primary_support_reason");

                    b.Property<string>("ResidentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resident_name");

                    b.Property<string>("SocialCareId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("social_care_id");

                    b.Property<LocalDate?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Instant?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<ReferralStatus>("Status")
                        .HasColumnType("referral_status")
                        .HasColumnName("status");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Instant?>("UrgentSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("urgent_since");

                    b.Property<decimal?>("WeeklyCost")
                        .HasColumnType("numeric")
                        .HasColumnName("weekly_cost");

                    b.Property<decimal?>("WeeklyPayment")
                        .HasColumnType("numeric")
                        .HasColumnName("weekly_payment");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_id");

                    b.Property<WorkflowType>("WorkflowType")
                        .HasColumnType("workflow_type")
                        .HasColumnName("workflow_type");

                    b.HasKey("Id")
                        .HasName("pk_care_packages");

                    b.HasIndex("AssignedApproverId")
                        .HasDatabaseName("ix__assigned_approver_id");

                    b.HasIndex("AssignedBrokerId")
                        .HasDatabaseName("ix__assigned_broker_id");

                    b.ToTable((string)null);

                    b.ToView("care_packages");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("CostCentre")
                        .HasColumnType("text")
                        .HasColumnName("cost_centre");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<List<decimal>>("DailyCosts")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric[]")
                        .HasColumnName("daily_costs")
                        .HasComputedColumnSql("ARRAY[COALESCE((monday->>'Cost')::numeric, 0), COALESCE((tuesday->>'Cost')::numeric, 0), COALESCE((wednesday->>'Cost')::numeric, 0), COALESCE((thursday->>'Cost')::numeric, 0), COALESCE((friday->>'Cost')::numeric, 0), COALESCE((saturday->>'Cost')::numeric, 0), COALESCE((sunday->>'Cost')::numeric, 0)]", true);

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int>("ElementTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("element_type_id");

                    b.Property<LocalDate?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<ElementCost?>("Friday")
                        .HasColumnType("jsonb")
                        .HasColumnName("friday");

                    b.Property<ElementStatus>("InternalStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("element_status")
                        .HasDefaultValue(ElementStatus.InProgress)
                        .HasColumnName("internal_status");

                    b.Property<bool>("IsSuspension")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_suspension");

                    b.Property<ElementCost?>("Monday")
                        .HasColumnType("jsonb")
                        .HasColumnName("monday");

                    b.Property<bool>("NonPersonalBudget")
                        .HasColumnType("boolean")
                        .HasColumnName("non_personal_budget");

                    b.Property<int?>("ParentElementId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_element_id");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<ElementCost?>("Saturday")
                        .HasColumnType("jsonb")
                        .HasColumnName("saturday");

                    b.Property<string>("SocialCareId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("social_care_id");

                    b.Property<LocalDate>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<ElementCost?>("Sunday")
                        .HasColumnType("jsonb")
                        .HasColumnName("sunday");

                    b.Property<int?>("SuspendedElementId")
                        .HasColumnType("integer")
                        .HasColumnName("suspended_element_id");

                    b.Property<ElementCost?>("Thursday")
                        .HasColumnType("jsonb")
                        .HasColumnName("thursday");

                    b.Property<ElementCost?>("Tuesday")
                        .HasColumnType("jsonb")
                        .HasColumnName("tuesday");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<ElementCost?>("Wednesday")
                        .HasColumnType("jsonb")
                        .HasColumnName("wednesday");

                    b.HasKey("Id")
                        .HasName("pk_elements");

                    b.HasIndex("ElementTypeId")
                        .HasDatabaseName("ix_elements_element_type_id");

                    b.HasIndex("ParentElementId")
                        .HasDatabaseName("ix_elements_parent_element_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_elements_provider_id");

                    b.HasIndex("SuspendedElementId")
                        .HasDatabaseName("ix_elements_suspended_element_id");

                    b.ToTable("elements", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.ElementType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<ElementBillingType>("Billing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("element_billing_type")
                        .HasDefaultValue(ElementBillingType.Supplier)
                        .HasColumnName("billing");

                    b.Property<int>("CostOperation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cost_operation");

                    b.Property<ElementCostType>("CostType")
                        .HasColumnType("element_cost_type")
                        .HasColumnName("cost_type");

                    b.Property<string>("FrameworkSubjectiveCode")
                        .HasColumnType("text")
                        .HasColumnName("framework_subjective_code");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsResidential")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_residential");

                    b.Property<bool>("IsS117")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_s117");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("NonPersonalBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("non_personal_budget");

                    b.Property<PaymentCycle>("PaymentCycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("payment_cycle")
                        .HasDefaultValue(PaymentCycle.Weekly)
                        .HasColumnName("payment_cycle");

                    b.Property<int>("PaymentOperation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("payment_operation");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("SubjectiveCode")
                        .HasColumnType("text")
                        .HasColumnName("subjective_code");

                    b.Property<ElementTypeType>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("element_type_type")
                        .HasDefaultValue(ElementTypeType.Service)
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_element_types");

                    b.HasIndex("ServiceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_element_types_service_id_name");

                    b.ToTable("element_types", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CedarNumber")
                        .HasColumnType("text")
                        .HasColumnName("cedar_number");

                    b.Property<string>("CedarSite")
                        .HasColumnType("text")
                        .HasColumnName("cedar_site");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Name", "Address" });

                    b.Property<ProviderType>("Type")
                        .HasColumnType("provider_type")
                        .HasColumnName("type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_providers");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_providers_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("CedarNumber", "CedarSite")
                        .IsUnique()
                        .HasDatabaseName("ix_providers_cedar_number_cedar_site");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedApproverEmail")
                        .HasColumnType("text")
                        .HasColumnName("assigned_approver_email");

                    b.Property<string>("AssignedBrokerEmail")
                        .HasColumnType("text")
                        .HasColumnName("assigned_broker_email");

                    b.Property<CareChargeStatus>("CareChargeStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("care_charge_status")
                        .HasDefaultValue(CareChargeStatus.New)
                        .HasColumnName("care_charge_status");

                    b.Property<Instant?>("CareChargesConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("care_charges_confirmed_at");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DirectPayments")
                        .HasColumnType("text")
                        .HasColumnName("direct_payments");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form_name");

                    b.Property<bool>("IsResidential")
                        .HasColumnType("boolean")
                        .HasColumnName("is_residential");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PrimarySupportReason")
                        .HasColumnType("text")
                        .HasColumnName("primary_support_reason");

                    b.Property<string>("ResidentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resident_name");

                    b.Property<string>("SocialCareId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("social_care_id");

                    b.Property<Instant?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<ReferralStatus>("Status")
                        .HasColumnType("referral_status")
                        .HasColumnName("status");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Instant?>("UrgentSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("urgent_since");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_id");

                    b.Property<WorkflowType>("WorkflowType")
                        .HasColumnType("workflow_type")
                        .HasColumnName("workflow_type");

                    b.HasKey("Id")
                        .HasName("pk_referrals");

                    b.HasIndex("AssignedApproverEmail")
                        .HasDatabaseName("ix_referrals_assigned_approver_email");

                    b.HasIndex("AssignedBrokerEmail")
                        .HasDatabaseName("ix_referrals_assigned_broker_email");

                    b.HasIndex("SocialCareId")
                        .IsUnique()
                        .HasDatabaseName("ix_referrals_social_care_id")
                        .HasFilter("status = 'in_progress' OR status = 'awaiting_approval'");

                    b.HasIndex("WorkflowId")
                        .IsUnique()
                        .HasDatabaseName("ix_referrals_workflow_id");

                    b.ToTable("referrals", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.ReferralAmendment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("ReferralId")
                        .HasColumnType("integer")
                        .HasColumnName("referral_id");

                    b.Property<Instant>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<AmendmentStatus>("Status")
                        .HasColumnType("amendment_status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_referral_amendments");

                    b.HasIndex("ReferralId")
                        .HasDatabaseName("ix_referral_amendments_referral_id");

                    b.ToTable("referral_amendments", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.ReferralElement", b =>
                {
                    b.Property<int>("ElementId")
                        .HasColumnType("integer")
                        .HasColumnName("element_id");

                    b.Property<int>("ReferralId")
                        .HasColumnType("integer")
                        .HasColumnName("referral_id");

                    b.Property<bool>("PendingCancellation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pending_cancellation");

                    b.Property<string>("PendingComment")
                        .HasColumnType("text")
                        .HasColumnName("pending_comment");

                    b.Property<LocalDate?>("PendingEndDate")
                        .HasColumnType("date")
                        .HasColumnName("pending_end_date");

                    b.HasKey("ElementId", "ReferralId")
                        .HasName("pk_referral_elements");

                    b.HasIndex("ReferralId")
                        .HasDatabaseName("ix_referral_elements_referral_id");

                    b.ToTable("referral_elements", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.ReferralFollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<LocalDate>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("ReferralId")
                        .HasColumnType("integer")
                        .HasColumnName("referral_id");

                    b.Property<Instant>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedByEmail")
                        .HasColumnType("text")
                        .HasColumnName("requested_by_email");

                    b.Property<FollowUpStatus>("Status")
                        .HasColumnType("follow_up_status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_referral_follow_ups");

                    b.HasIndex("ReferralId")
                        .HasDatabaseName("ix_referral_follow_ups_referral_id");

                    b.HasIndex("RequestedByEmail")
                        .HasDatabaseName("ix_referral_follow_ups_requested_by_email");

                    b.ToTable("referral_follow_ups", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Service", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("HasProvisionalClientContributions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_provisional_client_contributions");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_services_parent_id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.ServiceOverview", b =>
                {
                    b.Property<string>("SocialCareId")
                        .HasColumnType("text")
                        .HasColumnName("social_care_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal?>("AnnualCost")
                        .HasColumnType("numeric")
                        .HasColumnName("annual_cost");

                    b.Property<LocalDate?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<LocalDate>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<decimal?>("WeeklyCost")
                        .HasColumnType("numeric")
                        .HasColumnName("weekly_cost");

                    b.Property<decimal?>("WeeklyPayment")
                        .HasColumnType("numeric")
                        .HasColumnName("weekly_payment");

                    b.HasKey("SocialCareId", "Id");

                    b.ToTable((string)null);

                    b.ToView("service_overviews");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.ServiceUser", b =>
                {
                    b.Property<string>("SocialCareId")
                        .HasColumnType("text")
                        .HasColumnName("social_care_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<LocalDate>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<NpgsqlTsVector>("NameSearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("name_search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "ServiceUserName" });

                    b.Property<string>("ServiceUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_user_name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SocialCareId")
                        .HasName("pk_service_users");

                    b.ToTable("service_users", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ApprovalLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("approval_limit");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<List<UserRole>>("Roles")
                        .HasColumnType("user_role[]")
                        .HasColumnName("roles");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("Email")
                        .HasName("ak_users_email");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Workflow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DirectPayments")
                        .HasColumnType("text")
                        .HasColumnName("direct_payments");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form_name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PrimarySupportReason")
                        .HasColumnType("text")
                        .HasColumnName("primary_support_reason");

                    b.Property<int>("ReferralId")
                        .HasColumnType("integer")
                        .HasColumnName("referral_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Instant?>("UrgentSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("urgent_since");

                    b.Property<WorkflowType>("WorkflowType")
                        .HasColumnType("workflow_type")
                        .HasColumnName("workflow_type");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("ReferralId")
                        .HasDatabaseName("ix_workflows_referral_id");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.AuditEvents.AuditEvent", b =>
                {
                    b.HasOne("BrokerageApi.V1.Infrastructure.Referral", "Referral")
                        .WithMany()
                        .HasForeignKey("ReferralId")
                        .HasConstraintName("fk_audit_events_referrals_referral_id");

                    b.HasOne("BrokerageApi.V1.Infrastructure.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_events_users_user_id");

                    b.Navigation("Referral");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.CarePackage", b =>
                {
                    b.HasOne("BrokerageApi.V1.Infrastructure.User", "AssignedApprover")
                        .WithMany("ApproverCarePackages")
                        .HasForeignKey("AssignedApproverId")
                        .HasPrincipalKey("Email")
                        .HasConstraintName("fk__users_assigned_approver_id1");

                    b.HasOne("BrokerageApi.V1.Infrastructure.User", "AssignedBroker")
                        .WithMany("BrokerCarePackages")
                        .HasForeignKey("AssignedBrokerId")
                        .HasPrincipalKey("Email")
                        .HasConstraintName("fk__users_assigned_broker_id1");

                    b.Navigation("AssignedApprover");

                    b.Navigation("AssignedBroker");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Element", b =>
                {
                    b.HasOne("BrokerageApi.V1.Infrastructure.ElementType", "ElementType")
                        .WithMany("Elements")
                        .HasForeignKey("ElementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_elements_element_types_element_type_id");

                    b.HasOne("BrokerageApi.V1.Infrastructure.Element", "ParentElement")
                        .WithMany("ChildElements")
                        .HasForeignKey("ParentElementId")
                        .HasConstraintName("fk_elements_elements_parent_element_id");

                    b.HasOne("BrokerageApi.V1.Infrastructure.Provider", "Provider")
                        .WithMany("Elements")
                        .HasForeignKey("ProviderId")
                        .HasConstraintName("fk_elements_providers_provider_id");

                    b.HasOne("BrokerageApi.V1.Infrastructure.Element", "SuspendedElement")
                        .WithMany("SuspensionElements")
                        .HasForeignKey("SuspendedElementId")
                        .HasConstraintName("fk_elements_elements_suspended_element_id");

                    b.Navigation("ElementType");

                    b.Navigation("ParentElement");

                    b.Navigation("Provider");

                    b.Navigation("SuspendedElement");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.ElementType", b =>
                {
                    b.HasOne("BrokerageApi.V1.Infrastructure.Service", "Service")
                        .WithMany("ElementTypes")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_element_types_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Referral", b =>
                {
                    b.HasOne("BrokerageApi.V1.Infrastructure.User", "AssignedApprover")
                        .WithMany()
                        .HasForeignKey("AssignedApproverEmail")
                        .HasPrincipalKey("Email")
                        .HasConstraintName("fk_referrals_users_assigned_approver_id");

                    b.HasOne("BrokerageApi.V1.Infrastructure.User", "AssignedBroker")
                        .WithMany()
                        .HasForeignKey("AssignedBrokerEmail")
                        .HasPrincipalKey("Email")
                        .HasConstraintName("fk_referrals_users_assigned_broker_id");

                    b.Navigation("AssignedApprover");

                    b.Navigation("AssignedBroker");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.ReferralAmendment", b =>
                {
                    b.HasOne("BrokerageApi.V1.Infrastructure.CarePackage", null)
                        .WithMany("ReferralAmendments")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_referral_amendments_care_packages_care_package_id");

                    b.HasOne("BrokerageApi.V1.Infrastructure.Referral", "Referral")
                        .WithMany("ReferralAmendments")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_referral_amendments_referrals_referral_id");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.ReferralElement", b =>
                {
                    b.HasOne("BrokerageApi.V1.Infrastructure.Element", "Element")
                        .WithMany("ReferralElements")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_referral_elements_elements_element_id");

                    b.HasOne("BrokerageApi.V1.Infrastructure.CarePackage", "CarePackage")
                        .WithMany("ReferralElements")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_referral_elements_care_packages_care_package_id");

                    b.HasOne("BrokerageApi.V1.Infrastructure.Referral", "Referral")
                        .WithMany("ReferralElements")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_referral_elements_referrals_referral_id");

                    b.Navigation("CarePackage");

                    b.Navigation("Element");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.ReferralFollowUp", b =>
                {
                    b.HasOne("BrokerageApi.V1.Infrastructure.CarePackage", null)
                        .WithMany("ReferralFollowUps")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_referral_follow_ups_care_packages_care_package_id");

                    b.HasOne("BrokerageApi.V1.Infrastructure.Referral", "Referral")
                        .WithMany("ReferralFollowUps")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_referral_follow_ups_referrals_referral_id");

                    b.HasOne("BrokerageApi.V1.Infrastructure.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedByEmail")
                        .HasPrincipalKey("Email")
                        .HasConstraintName("fk_referral_follow_ups_users_requested_by_id");

                    b.Navigation("Referral");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Service", b =>
                {
                    b.HasOne("BrokerageApi.V1.Infrastructure.Service", "Parent")
                        .WithMany("Services")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_services_services_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Workflow", b =>
                {
                    b.HasOne("BrokerageApi.V1.Infrastructure.CarePackage", null)
                        .WithMany("Workflows")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflows_care_packages_care_package_id");

                    b.HasOne("BrokerageApi.V1.Infrastructure.Referral", "Referral")
                        .WithMany("Workflows")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflows_referrals_referral_id");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.CarePackage", b =>
                {
                    b.Navigation("ReferralAmendments");

                    b.Navigation("ReferralElements");

                    b.Navigation("ReferralFollowUps");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Element", b =>
                {
                    b.Navigation("ChildElements");

                    b.Navigation("ReferralElements");

                    b.Navigation("SuspensionElements");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.ElementType", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Provider", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Referral", b =>
                {
                    b.Navigation("ReferralAmendments");

                    b.Navigation("ReferralElements");

                    b.Navigation("ReferralFollowUps");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.Service", b =>
                {
                    b.Navigation("ElementTypes");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("BrokerageApi.V1.Infrastructure.User", b =>
                {
                    b.Navigation("ApproverCarePackages");

                    b.Navigation("BrokerCarePackages");
                });
#pragma warning restore 612, 618
        }
    }
}
